## 1. 手写call
```js
var name = 'jl';

var obj = {
  name: '江路';
}

function fn(a, b, c) {
  console.log(a + b + c + this.name)
}

Function.prototype.mycall = function(obj) {
  if (typeof this !== 'function') {
      throw new TypeError('error')
  }
  // call的第一个参数可以是null
  obj = obj || window;

  var args = [];

  for (var i = 1, len = arguments.length; i < len; i++) {
    args.push("arguments["+i+"]")
  }

  // 最重要一步！说明两个问题： 1. mycall内部的this指向调用者fn函数（对象的） 2. obj.func就是fn函数，因此fn函数内部的this指向obj
  obj.func = this;
  // eval(obj.fn(args))
  const res = eval("obj.func("+args+")")
  delete obj.func;
  return res;
}

// 函数也是对象，因此这里的fn作为函数对象调用了额mycall
// this总是指向他的调用者，因此
fn.mycall(obj, '我的', '名字', '是')
```

## 2. 手写apply
```js
var name = 'jl';

var obj = {
  name: '江路';
}

function fn(a, b, c) {
  console.log(a + b + c + this.name)
}

Function.prototype.myapply = function(obj, arr) {
  if (typeof this !== 'function') {
      throw new TypeError('error')
  }
  // call的第一个参数可以是null
  obj = obj || window;

  let res = null;

  if(!arr) {
    obj.func = this;
    res = obj.func()
  } else {
    var args = [];

    for (let i = 0, len = arr.length; i < len; i++) {
      args.push("arr["+i+"]")
    }

    // 最重要一步！说明两个问题： 1. mycall内部的this指向调用者fn函数（对象的） 2. obj.func就是fn函数，因此fn函数内部的this指向obj
    obj.func = this;
    res = eval("obj.func("+args+")")
  }
  delete obj.func;
  return res;
}

// 函数也是对象，因此这里的fn作为函数对象调用了额mycall
// this总是指向他的调用者，因此
fn.myapply(obj, ['我的', '名字', '是'])
```